"""DIMER inference package for the pinned ``google/pix2struct-docvqa-base`` checkpoint."""

from .pipeline import (
    ANLS_THRESHOLD,
    DECODING,
    DEFAULT_MAX_NEW_TOKENS,
    DEFAULT_WEIGHTS_DIR,
    INPUT_SCHEMA,
    MAX_IMAGE_SIDE,
    MAX_NEW_TOKENS,
    MAX_PATCHES,
    MAX_QUESTION_CHARS,
    MIN_IMAGE_SIDE,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    Pix2StructDocVQAPipeline,
    anls,
    evaluation_report,
    exact_match,
    header_font_bytes,
    normalize_answer,
    stage_missing_files,
    validate_inputs,
    verify_snapshot,
)

__all__ = [
    "ANLS_THRESHOLD",
    "DECODING",
    "DEFAULT_MAX_NEW_TOKENS",
    "DEFAULT_WEIGHTS_DIR",
    "INPUT_SCHEMA",
    "MAX_IMAGE_SIDE",
    "MAX_NEW_TOKENS",
    "MAX_PATCHES",
    "MAX_QUESTION_CHARS",
    "MIN_IMAGE_SIDE",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "Pix2StructDocVQAPipeline",
    "anls",
    "evaluation_report",
    "exact_match",
    "header_font_bytes",
    "normalize_answer",
    "stage_missing_files",
    "validate_inputs",
    "verify_snapshot",
]
